AWSTemplateFormatVersion: "2010-09-09"
Description: IAM automation lab with users, groups, and secrets manager password

Resources:
  # Random secret password for the user
  IAMSecretpassword:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "IAMLabTemporaryPassword"
      GenerateSecretString:
        PasswordLength: 12
        ExcludePunctuation: true

  # ===============
  # IAM GROUPS
  # ==============

  # EC2 Group
  EC2Group:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "EC2Group"


# S3 Group
  S3Group:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "S3Group"
  


  # ================
  # Group Policies
  # ================


# EC2 Group Policy
  EC2Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "EC2GroupPolicy"
      Groups:
        - "EC2Group"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ec2:DescribeInstances"
              - "ec2:RunInstances"
            Resource: "*"


# S3 Group Policy
  S3Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "S3GroupPolicy"
      Groups:
        - "S3Group"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:ListBucket"
              - "s3:ListAllMyBuckets"
            Resource: "*"


# ================
# IAM USERS
# ================


# EC2 User
  EC2User1:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "EC2User"
      Groups:
        - "EC2Group"
      LoginProfile:
        Password: "{{resolve:secretsmanager:IAMLabTemporaryPassword:SecretString}}"
        PasswordResetRequired: true


# EC2 User 2
  EC2User2:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "EC2User2"
      Groups:
        - "EC2Group"
      LoginProfile:
        Password: "{{resolve:secretsmanager:IAMLabTemporaryPassword:SecretString}}"
        PasswordResetRequired: true

  # S3 User
  S3User1:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "S3User1"
      Groups:
        - "S3Group"
      LoginProfile:
        Password: "{{resolve:secretsmanager:IAMLabTemporaryPassword:SecretString}}"
        PasswordResetRequired: true



Outputs:
  SecretArn:
    Description: "ARN of the generated secret password"
    Value:
      Ref IAMSecretpassword