AWSTemplateFormatVersion: "2010-09-09"

Description: A simple CloudFormation template to create an S3 bucket.

Resources:
  MySecondBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "my-second-bucket-1234567890"

Outputs:
  BucketName:
    Description: The name of the created S3 bucket
    Value:
      Ref: MySecondBucket