AWSTemplateFormatVersion: "2010-09-09"
Description: Tighten your IAM Permissions 



Parameters:
  EnvironmentName:
    Type: String
    Default: production

  KeyAdminRoleArn:
    Type: String
    Description: "ARN of the IAM role that will administer the KMS key"

  AppRoleArn:
    Type: String
    Description: "ARN of the IAM role that will use the key in cryptographic operations (e.g. ECS Task Role)"


Resources:
  
  Level1SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for Level 1 Security Lab" 
      VpcId: vpc-0bde4c384335984d4
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 800
          CidrIp: 0.0.0.0/0



# ===============
# EC2
# ===============

# EC2 Role with S3 read access
  EC2S3ReadRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "ec2-s3-read-access"
      AssumeRolePolicyDocument:
        Name: "EC2S3ReadAccessAssumeRolePolicy"
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
      Description: "Role for EC2 to read s3 buckets"

# EC2 Instance Profile for EC2S3ReadRole
  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref EC2S3ReadRole

  # EC2 Instance with EC2S3ReadRole
  MyEc2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0a0823e4ea064404d
      InstanceType: "t3.micro"
      IamInstanceProfile: !Ref EC2InstanceProfile


# ===============
# Lambda
# ===============

# Lambda Role with S3 read access
  LambdaS3ReadRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "lambda-s3-read-only"
      AssumeRolePolicyDocument:
        Name: "LambdaS3ReadAccessAssumeRolePolicy"
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
      Description: "Role for Lambda to read s3 buckets"

# LAmbda Function with LambdaS3ReadRole
  MyLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "MyS3ReadOnlyLambda"
      Runtime: "python3.8"
      Role: !GetAtt LambdaS3ReadRole.Arn
      Handler: "lambda_function.lambda_handler"
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return "Hello from Lambda with S3 Read-Only Access!"



# ============================================================================================================================================================
# ===============
# ECS
# ===============

# Task Execution Role 
  ECSTaskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${AWS::StackName}-ecs-task-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      Description: "Role for ECS tasks to execute and pull images from ECR"


  # ECS EC2 Instance Role
  ECSInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${AWS::StackName}-ecs-instance-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
      Description: "Role for EC2 instances in ECS cluster"

  # Instance Profile for ECS EC2 Instance Role
  ECSInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref ECSInstanceRole

  # IAM ROLE FOR TASKS
  ECSTasksS3BucketRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${AWS::StackName}-ecs-tasks-s3-access-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
      Description: "Role for ECS tasks to read from S3 buckets"



# ============================================================================================================================================================


      # Systems manager parameter Store
  ProductionKMSKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: "KMS Key for encrypting ssm parameter Store secrets"
      Enabled: true
      EnableKeyRotation: true
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      PendingWindowInDays: 30
      KeyPolicy: 
        Version: "2012-10-17"
        Statement:

        # Root account full control
          - Sid: "EnableRootAccountAccess"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"


            # Key administrators - manage but Not use cryptographically
          - Sid: "AllowKeyAdministration"
            Effect: "Allow"
            Principal:
              AWS: !GetAtt KeyAdminRole.Arn
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:TagResource"
              - "kms:UntagResource"
              - "kms:CancelKeyDeletion"
            Resource: "*"


            # SSM Service - needed to encrypt/decrypt SecureString params
          - Sid: "AllowSSMServiceUse"
            Effect: Allow
            Principal:
              Service: "ssm.amazonaws.com"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey*"
            Resource: "*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
    Tags:
      - Key: "Environment"
        Value: !Ref EnvironmentName
      - Key: "ManagedBy"
        Value: "CloudFormation"


  KeyAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "sts:AssumeRole"

  ProductionKMSKeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-production-kms-key"
      TargetKeyId: !Ref ProductionKMSKey


# =============================================================
  # 2. SSM PARAMETER STORE — SecureString parameter
  #    Hierarchical naming: /production/database/keys
  # =============================================================

  ProductionDatabaseKeyParams:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/production/database/keys"
      Description: "Production database encryption keys"
      Type: SecureString
      KeyId: !Ref ProductionKMSKey
      Value: "initial-demo-value"




# ============================================================================================================================================================
# SECRET MANAGER


  ProductionAppSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "tutorial/MyFirstSecret"
      Description: "Access credentials for production API"
      KmsKeyId: !Ref ProductionKMSKey
      SecretString: '{"MyPassword":"initial-demo-secret-value"}'